#!/usr/bin/env node
/**
 * Epistemic Commons — data compiler.
 * Reads the codices (markdown + frontmatter) and the manifesto, and emits
 * site/data/documents.js as a classic script (window.EC.*) so the site works
 * from file:// as well as over http.
 *
 * Usage: node tools/build-data.mjs
 */
import { readFileSync, writeFileSync, readdirSync, statSync } from "node:fs";
import { join, dirname, basename } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const CODICES_DIR = join(ROOT, "codices", "uk");
const OUT = join(ROOT, "site", "data", "documents.js");

/* ---------- minimal YAML-subset frontmatter parser ----------
 * Supports: `key: value`, `key: [a, b]`, and block lists of flat maps:
 *   key:
 *     - name: x
 *       role: y
 */
function unquote(v) {
  v = v.trim();
  if ((v.startsWith('"') && v.endsWith('"')) || (v.startsWith("'") && v.endsWith("'"))) {
    return v.slice(1, -1);
  }
  return v;
}

function parseFrontmatter(text) {
  const meta = {};
  const lines = text.split("\n");
  let listKey = null;
  let current = null;

  for (const raw of lines) {
    if (!raw.trim()) continue;
    const topMatch = raw.match(/^([A-Za-z][\w-]*):\s*(.*)$/);
    const itemStart = raw.match(/^\s+-\s+([\w-]+):\s*(.*)$/);
    const itemCont = raw.match(/^\s+([\w-]+):\s*(.*)$/);

    if (topMatch && !raw.startsWith(" ")) {
      const [, key, value] = topMatch;
      if (value === "") {
        listKey = key;
        meta[key] = [];
        current = null;
      } else if (value.startsWith("[") && value.endsWith("]")) {
        meta[key] = value.slice(1, -1).split(",").map((s) => unquote(s)).filter(Boolean);
        listKey = null;
      } else {
        meta[key] = unquote(value);
        listKey = null;
      }
    } else if (listKey && itemStart) {
      current = { [itemStart[1]]: unquote(itemStart[2]) };
      meta[listKey].push(current);
    } else if (listKey && current && itemCont) {
      current[itemCont[1]] = unquote(itemCont[2]);
    }
  }
  return meta;
}

function parseDoc(path) {
  const raw = readFileSync(path, "utf8");
  const match = raw.match(/^---\n([\s\S]*?)\n---\n?([\s\S]*)$/);
  if (!match) throw new Error(`No frontmatter in ${path}`);
  return { meta: parseFrontmatter(match[1]), body: match[2].trim() };
}

/* ---------- walk the codices ---------- */
const codices = [];
const documents = [];

for (const dir of readdirSync(CODICES_DIR).sort()) {
  const full = join(CODICES_DIR, dir);
  if (!statSync(full).isDirectory()) continue;

  const files = readdirSync(full).filter((f) => f.endsWith(".md")).sort();
  const preamblePath = join(full, "PREAMBLE.md");
  const preamble = parseDoc(preamblePath);

  const codex = {
    key: dir,
    title: preamble.meta.title || dir,
    description: preamble.meta.description || "",
    custodian: preamble.meta.custodian || "",
    polity: preamble.meta.polity || "uk",
    preamble: preamble.body,
    documents: [],
  };

  for (const f of files) {
    if (f === "PREAMBLE.md") continue;
    const { meta, body } = parseDoc(join(full, f));
    const doc = {
      id: meta.id || basename(f, ".md"),
      codex: dir,
      file: `codices/uk/${dir}/${f}`,
      title: meta.title,
      citation: meta.citation || "",
      type: meta.type || "",
      status: meta.status || "",
      themes: meta.themes || [],
      source: meta.source || "",
      custodian: meta.custodian || "",
      sponsors: meta.sponsors || [],
      inscriptions: meta.inscriptions || [],
      body,
    };
    documents.push(doc);
    codex.documents.push(doc.id);
  }

  // codex stats
  const docs = documents.filter((d) => d.codex === dir);
  const years = docs
    .flatMap((d) => d.inscriptions.map((i) => parseInt(String(i.date).slice(0, 4), 10)))
    .filter((y) => !Number.isNaN(y));
  codex.stats = {
    documents: docs.length,
    inscriptions: docs.reduce((n, d) => n + d.inscriptions.length, 0),
    sponsors: docs.reduce((n, d) => n + d.sponsors.length, 0),
    from: Math.min(...years),
    to: Math.max(...years),
  };
  codices.push(codex);
}

/* ---------- manifesto ---------- */
const manifesto = parseDoc(join(ROOT, "manifesto", "rationalist-manifesto.md"));

/* ---------- emit ---------- */
const payload =
  "// Generated by tools/build-data.mjs — do not edit by hand.\n" +
  "// Source of truth: /codices and /manifesto markdown files.\n" +
  "window.EC = window.EC || {};\n" +
  `window.EC.codices = ${JSON.stringify(codices, null, 1)};\n` +
  `window.EC.documents = ${JSON.stringify(documents, null, 1)};\n` +
  `window.EC.manifesto = ${JSON.stringify({ meta: manifesto.meta, body: manifesto.body }, null, 1)};\n`;

writeFileSync(OUT, payload);
console.log(
  `Compiled ${codices.length} codices, ${documents.length} documents → ${OUT} (${(payload.length / 1024).toFixed(1)} kB)`
);
